LANGUAGE:
  - JAVA
  - node_js
SUDO: FALSE
node_js:
  - 7
before_script:
  - npm install qunit
  - npm install request
SCRIPT:
  - cd back/
  - mvn install
  - cd ../front
  - qunit  'tests/test_connection_servers.js'
